# Generated by Django 3.0.4 on 2020-03-26 00:19

import apps.channel.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='videoChannel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Date of Create')),
                ('date_change', models.DateField(auto_now=True, verbose_name='Date of Change')),
                ('date_delete', models.DateField(auto_now=True, verbose_name='Date of Delete')),
                ('date_time_c', models.TimeField(auto_now_add=True)),
                ('date_time_m', models.TimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name Video')),
                ('description', models.TextField(blank=True, max_length=1800, null=True, verbose_name='Description')),
                ('video', models.FileField(blank=True, null=True, upload_to=apps.channel.models.RutaVideo)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='channel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Date of Create')),
                ('date_change', models.DateField(auto_now=True, verbose_name='Date of Change')),
                ('date_delete', models.DateField(auto_now=True, verbose_name='Date of Delete')),
                ('date_time_c', models.TimeField(auto_now_add=True)),
                ('date_time_m', models.TimeField(auto_now=True)),
                ('name_channel', models.CharField(max_length=80, verbose_name='Name Channel')),
                ('status', models.BooleanField(default=True)),
                ('ip', models.CharField(max_length=16, verbose_name='IP')),
                ('mac', models.CharField(max_length=20, verbose_name='MacAddress')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.videoChannel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
