# Generated by Django 3.0.4 on 2020-03-26 02:40

import apps.channel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_videochannel_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videochannel',
            name='img',
        ),
        migrations.AddField(
            model_name='channel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=apps.channel.models.RutaVideo),
        ),
    ]
